project/appointments/forms.py
__author__ = 'mosquito'
from flask_wtf import Form
from wtforms import StringField, DateTimeField, IntegerField, \
    SelectField
from wtforms.validators import DataRequired


class AddAppointmentForm(Form):
    appointment_id = IntegerField('Priority')
    name = StringField('Appointment Name', validators=[DataRequired()])
    due_date = DateTimeField('Date Due (YYYY-mm-dd HH:MM:ss)', validators=[DataRequired()], format='%Y-%m-%d %H:%M:%S')
    priority = SelectField('Priority', validators=[DataRequired()], choices=[
                                            ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5','5'),
                                            ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10','10')])

project/appointments/views.py
__author__ = 'mosquito'

#################
#### imports ####
#################

from functools import wraps
from flask import flash, redirect, render_template, \
    request, session, url_for, Blueprint
from sqlalchemy.exc import IntegrityError
import datetime
from time import localtime, strftime

from project.appointments.forms import AddAppointmentForm
from project import db
from project.models import Appointment


################
#### config ####
################

appointments_blueprint = Blueprint('appointments', __name__)

##########################
#### helper functions ####
##########################


def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('users.login'))
    return wrap


def open_appointments():
    return db.session.query(Appointment).filter_by(status='1')\
        .order_by(Appointment.due_date.asc())


def closed_appointments():
    return db.session.query(Appointment).filter_by(status='0')\
        .order_by(Appointment.due_date.asc())

################
#### routes ####
################

@appointments_blueprint.route('/appointments/')
@login_required
def appointments():
    # Get current date
    current_datetime = strftime("%Y-%m-%d %H:%M:%S", localtime())
    if session['role'] == u'admin':
        future_appointments = db.session.query(Appointment)\
            .filter(Appointment.due_date >= current_datetime)\
            .order_by(Appointment.due_date.asc())
        past_appointments = db.session.query(Appointment)\
            .filter(Appointment.due_date < current_datetime)\
            .order_by(Appointment.due_date.asc())
    else:
        future_appointments = db.session.query(Appointment)\
            .filter(Appointment.due_date >= current_datetime)\
            .filter(Appointment.user_id == session['user_id'])\
            .order_by(Appointment.due_date.asc())
        past_appointments = db.session.query(Appointment)\
            .filter(Appointment.due_date < current_datetime)\
            .filter(Appointment.user_id == session['user_id'])\
            .order_by(Appointment.due_date.asc())
    return render_template('appointments.html',
        form = AddAppointmentForm(request.form),
        future_appointments=future_appointments,
        past_appointments=past_appointments,
        username=session['name'])

@appointments_blueprint.route('/add/', methods=['GET', 'POST'])
@login_required
def new_appointment():
    error = None
    form = AddAppointmentForm(request.form)
    if request.method == 'POST':
        if form.validate():
            if form.validate_on_submit():
                new_appointment = Appointment(
                    form.name.data,
                    form.due_date.data,
                    form.priority.data,
                    datetime.datetime.utcnow(),
                    session['user_id']
                )
                db.session.add(new_appointment)
                db.session.commit()
                flash('New entry was successfully posted. Thanks.')
        else:
            return render_template("appointments.html", form=form)
    return redirect(url_for('appointments.appointments'))


@appointments_blueprint.route('/delete/<int:appointment_id>/')
@login_required
def delete_entry(appointment_id):
    apo_id = appointment_id
    appointment = db.session.query(Appointment).filter_by(appointment_id=apo_id)
    if session['user_id'] == appointment.first().user_id or session['role'] == "admin":
        appointment.delete()
        db.session.commit()
        flash('The appointment was deleted successfully')
        return redirect(url_for('appointments.appointments'))
    else:
        flash('You can only delete appointments that you have created')
        return redirect(url_for('appointments.appointments'))

project/users/views.py
__author__ = 'mosquito'

#################
#### imports ####
#################

from functools import wraps
from flask import flash, redirect, render_template, \
    request, session, url_for, Blueprint
from sqlalchemy.exc import IntegrityError

from project.users.forms import RegisterForm, LoginForm
from project import db, bcrypt
from project.models import User

#######################
#### configuration ####
#######################

users_blueprint = Blueprint('users', __name__)

##########################
#### helper_functions ####
##########################


def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('users.login'))
    return wrap

##########################
#######  routes  #########
##########################

@users_blueprint.route('/logout/')
@login_required
def logout():
    session.pop('logged_in', None)
    session.pop('user_id', None)
    session.pop('role', None)
    session.pop('name', None)
    flash('You are logged out. Bye. :(')
    return redirect(url_for('users.login'))

@users_blueprint.route('/', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(name=request.form['name']).first()
            if user is not None and bcrypt.check_password_hash(user.password, request.form['password']):
                session['logged_in'] = True
                session['user_id'] = user.id
                session['role'] = user.role
                session['name'] = user.name
                flash('You are logged in. Schedule like mad!')
                return redirect(url_for('appointments.appointments'))
            else:
                error = 'Could not find any user with provided user name or password.'
                return render_template('login.html', form=form, error=error)
    return render_template('login.html', form=form, error=error)

@users_blueprint.route('/register/', methods=['GET', 'POST'])
def register():
    error = None
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_user = User(
            form.name.data,
            form.email.data,
            bcrypt.generate_password_hash(form.password.data),
            )
            try:
                db.session.add(new_user)
                db.session.commit()
                flash('New user created successfully. Please login.')
                return redirect(url_for('users.login'))
            except IntegrityError:
                error = 'Provided username and password exist already, try again with different values'
                return render_template('register.html', form=form, error=error)
    return render_template('register.html', form=form, error=error)

project/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Scheduler</title>

    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">FlaskScheduler</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    {% if not session.logged_in %}
                        <li><a href="{{ url_for('users.register') }}">Signup</a></li>
                    {% else %}
                        <li><a href="{{ url_for('users.logout') }}">Signout</a></li>
                    {% endif %}
                </ul>
                {% if session.logged_in %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a>Welcome, {{username}}.</a></li>
                    </ul>
                {% endif %}
        </div><!--/.nav-collapse -->
        </div>
    </div>
    <div class="container">
      <div class="starter-template">
        <img class="img-responsive" src="{{ url_for('static', filename='img/logo.png') }}">
        {% for message in get_flashed_messages() %}
        <div class="flash">
            <p class="text-info">{{ message }}</p>
        </div>
        {% endfor %}
        {% if error %}
            <p class="text-error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

        {% block content %}
        {% endblock %}
      </div>
    </div><!-- /.container -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  </body>
</html>

project/templates/appointments.html
{% extends "_base.html" %}
{% block content %}
<div>
    <a class="btn btn-danger" href="/logout">Logout</a>
</div>
<div class="add-task">
    <h3>Add a new appointment:</h3>
        <form class="form-horizontal" action="{{ url_for('appointments.new_appointment') }}" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                <label >Name:</label>
                <input type="text" class="form-control" name="name" placeholder="Name">
                <span class="error">
                    {% if form.name.errors %}
                        {% for error in form.name.errors %}
                            {{ error }}
                        {% endfor %}
                    {% endif %}
                </span>
            </div>
            <div class="form-group">
                <label>Due Date (yyyy-mm-dd):</label>
                <input type="text" name="due_date" class="form-control" placeholder="i.e. 2015-03-15 19:30:00">
                <span class="error">
                    {% if form.due_date.errors %}
                        {% for error in form.due_date.errors %}
                            {{ error }}
                        {% endfor %}
                    {% endif %}
                </span>
            </div>
            <div class="form-group">
                <label>Priority:</label>
                <select name="priority" width="100px">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                </select>
            </div>
             <div class="form-group">
                <button type="submit" class="btn btn-success" value="Save">Save</button>
             </div>
        </form>
</div>
<div class="entries">
    <br>
    <br>
    <h3>Future appointments:</h3>
    <div class="datagrid">
        <table class="table">
            <thead>
                <tr>
                    <th>Appointment</th>
                    <th>Due Date</th>
                    <th>Priority</th>
                    <th>Posted Date</th>
                    <th>Posted By</th>
                </tr>
            </thead>
            {% for o in future_appointments %}
            <tr>
                <td>{{ o.name }}</td>
                <td>{{ o.due_date }}</td>
                <td>{{ o.priority }}</td>
                <td>{{ o.posted_date }}</td>
                <td >{{ o.poster.name }}</td>
                <td>
                    <a href="{{ url_for('appointments.delete_entry', appointment_id = o.appointment_id) }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <br>
    <br>
</div>
<div class="entries">
    <h3>Past appointments:</h3>
    <div class="datagrid">
        <table class="table">
            <thead>
                <tr>
                    <th>Appointment</th>
                    <th>Due Date</th>
                    <th>Priority</th>
                    <th>Posted Date</th>
                    <th>Posted By</th>
                </tr>
            </thead>
            {% for c in past_appointments %}
                <tr>
                    <td>{{ c.name }}</td>
                    <td>{{ c.due_date }}</td>
                    <td>{{ c.priority }}</td>
                    <td>{{ c.posted_date }}</td>
                    <td >{{ c.poster.name }}</td>
                    <td>
                        <a href="{{ url_for('appointments.delete_entry', appointment_id = c.appointment_id) }}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

project/templates/error_404.html
{% extends "_base.html" %}

{% block content %}

<h1>404</h1>
<p>Believe it or not, you've found a dead link!!! A special team of Black Mesa scientists are investigating right now.</p>
<p>In the meantime, you can <a href="{{url_for('users.login')}}"> go back home</a></p>

{% endblock %}

project/templates/error_500.html
{% extends "_base.html" %}

{% block content %}

<h1>500</h1>
<p>Server crashed! We're running in circles trying to fix it, stay tuned!</p>
<p>In the meantime, you can <a href="{{url_for('users.login')}}"> go back home</a></p>

{% endblock %}

project/templates/login.html
{% extends "_base.html" %}
{% block content %}
        <h2>Welcome to the Flask Scheduler!</h2>
        <h3>Please login to access your scheduler.</h3>
            <form action="" class="form-inline" method="post">
                {{ form.csrf_token }}
                <div class="form-group">
                    <label>Username:</label>
                    <input type="text" class="form-control" name="name" placeholder="User name" value="{{request.form.name }}">
                    <span class="error">
                        {% if form.name.errors %}
                            {% for error in form.name.errors %}
                                {{ error }}
                            {% endfor %}
                        {% endif %}
                    </span>
                </div>
                <div class="form-group">
                    <label>Password:</label>
                    <input type="password" class="form-control" name="password" placeholder="Password" value="{{request.form.password }}">
                    <span class="error">
                        {% if form.password.errors %}
                            {% for error in form.password.errors %}
                                {{ error }}
                            {% endfor %}
                        {% endif %}
                    </span>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
                <a class="btn btn-danger" href="/register">Register</a>
            </form>
            <br>
        <br>

{% endblock %}

project/templates/main.html
{% extends "_base.html" %}
{% block content %}
    <h2>Welcome to the Flask Scheduler!</h2>
    <p><a href="/logout">Logout</a></p>
    <h3>Add a new post:</h3>
        <form action="{{ url_for('add') }}" method="post" class="add">
            <div class="form-group">
                <label>Title:</label>
                <input type="text" class="form-control" placeholder="Enter post title">
            </div>
            <div class="form-group">
                <label>Post:</label>
                <textarea class="form-control" rows="3"></textarea>
            </div>
            <div class="form-group">

            </div>

            <input class="btn btn-inverse" type="submit" value="Save">
        </form>
    <br>
    <br>
    <h3>Posts:</h3>
    {% for p in posts %}
        <strong>Title:</strong> {{ p.title }} <br/>
        <strong>Post:</strong> {{ p.post }} <br/>
    <br/>
    {% endfor %}
{% endblock %}

project/templates/register.html
{% extends "_base.html" %}
{% block content %}
    <h3>Register new user</h3>
    <form action="" class="form-horizontal" method="post">
        {{ form.csrf_token }}
        <div class="form-group">
            <label>Username:</label>
            <input type="text" class="form-control" name="name" placeholder="User name" value="{{request.form.name }}">
            <span class="error">
                {% if form.name.errors %}
                    {% for error in form.name.errors %}
                        {{ error }}
                    {% endfor %}
                {% endif %}
            </span>
        </div>
        <div class="form-group">
            <label>Email:</label>
            <input type="text" class="form-control" name="email" placeholder="Email" value="{{request.form.email }}">
             <span class="error">
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        {{ error }}
                    {% endfor %}
                {% endif %}
            </span>
        </div>
        <div class="form-group">
            <label>Password:</label>
            <input type="password" class="form-control" name="password" placeholder="Password" value="{{request.form.password }}">
            <span class="error">
                {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        {{ error }}
                    {% endfor %}
                {% endif %}
            </span>
        </div>
        <div class="form-group">
            <label>Confirm Password:</label>
            <input type="password" class="form-control" name="confirm" placeholder="Confirm password" value="{{request.form.confirm }}">
            <span class="error">
                {% if form.confirm.errors %}
                    {% for error in form.confirm.errors %}
                        {{ error }}
                    {% endfor %}
                {% endif %}
            </span>
        </div>
        <button type="submit" value="Register" class="btn btn-primary">Register</button>
    </form>
    <p><em>Already registered?</em> Click <a href="/">here</a> to login.</p>
{% endblock %}